platform :ios, '10.0'

# pod 'HaishinKit'
# pod 'LFLiveKit', git: 'https://github.com/17media/LFLiveKit.git'

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# config.build_settings['ENABLE_BITCODE'] = 'NO'
			config.build_settings['SWIFT_SWIFT3_OBJC_INFERENCE'] = 'On'
		end
	end
end
